#!/bin/bash
set -euo pipefail

# =============================================================================
# Ubuntu Minimal WireGuard VPN Server Setup Script
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VPN_CONF_FILE="${VPN_CONF_FILE:-${SCRIPT_DIR}/../../vpn.conf}"
if [ -f "$VPN_CONF_FILE" ]; then
    . "$VPN_CONF_FILE"
fi

WG_INTERFACE="${WG_INTERFACE:-wg0}"
WG_PORT="${WG_PORT:-51820}"
WG_SERVER_ADDRESS="${WG_SERVER_ADDRESS:-10.8.0.1/24}"
WG_SERVER_PEER_ALLOWED_IPS="${WG_SERVER_PEER_ALLOWED_IPS:-10.8.0.2/32}"
WG_CONFIG_DIR="/etc/wireguard"
WG_PRIVATE_KEY_FILE="${WG_CONFIG_DIR}/privatekey"
WG_PUBLIC_KEY_FILE="${WG_CONFIG_DIR}/publickey"
ADMIN_USER="${ADMIN_USER:-}"
CLIENT_PUBLIC_KEY="${CLIENT_PUBLIC_KEY:-}"
ENABLE_SSH="${ENABLE_SSH:-false}"
WAN_INTERFACE=""

echo_info() {
    echo "[INFO] $1"
}

echo_warn() {
    echo "[WARN] $1"
}

echo_error() {
    echo "[ERROR] $1" >&2
    exit 1
}

get_admin_user() {
    if [ -z "${ADMIN_USER:-}" ]; then
        ADMIN_USER=$(LC_ALL=C tr -dc 'a-z' </dev/urandom | head -c 12 || true)
    fi

    if [ "${#ADMIN_USER}" -ne 12 ]; then
        echo_error "ADMIN_USER must be 12 alphabetic characters."
    fi
}

get_public_ip() {
    if [ -z "${SERVER_PUBLIC_IP:-}" ]; then
        echo_error "SERVER_PUBLIC_IP is required."
    fi

    echo "$SERVER_PUBLIC_IP"
}

get_client_public_key() {
    if [ -z "${CLIENT_PUBLIC_KEY:-}" ]; then
        echo_error "CLIENT_PUBLIC_KEY is required. The client key pair must be generated by the caller; the server only receives the client public key."
    fi
}

get_wan_interface() {
    WAN_INTERFACE=$(ip -o route show default 2>/dev/null | awk '{print $5; exit}')
    if [ -z "$WAN_INTERFACE" ]; then
        echo_warn "Could not detect default WAN interface; falling back to eth0."
        WAN_INTERFACE="eth0"
    fi
}

get_admin_user
get_client_public_key
get_wan_interface

echo_info "Updating package index and installing WireGuard..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends wireguard-tools iptables iptables-persistent curl sudo

if [ "$ENABLE_SSH" = "true" ]; then
    echo_info "Debug mode: installing SSH server..."
    apt-get install -y --no-install-recommends openssh-server
fi

if ! modprobe wireguard 2>/dev/null; then
    echo_warn "WireGuard kernel module not available; the image/kernel may already provide it."
fi

echo_info "Creating admin user..."
if ! id "$ADMIN_USER" &>/dev/null; then
    adduser --disabled-password --gecos "" "$ADMIN_USER" || echo_error "Failed to create admin user."
fi

# Key-based authentication only: the account has no password (issue #2).
# Grant passwordless sudo so administrative tasks remain possible over SSH
# without ever handling a cleartext password.
usermod -aG sudo "$ADMIN_USER" || echo_error "Failed to add admin user to sudo group."
printf '%s ALL=(ALL) NOPASSWD:ALL\n' "$ADMIN_USER" > "/etc/sudoers.d/90-${ADMIN_USER}"
chmod 440 "/etc/sudoers.d/90-${ADMIN_USER}"

echo_info "Preparing configuration directories..."
mkdir -p "$WG_CONFIG_DIR"

echo_info "Generating WireGuard server keys..."
wg genkey | tee "$WG_PRIVATE_KEY_FILE" | wg pubkey > "$WG_PUBLIC_KEY_FILE"
chmod 600 "$WG_PRIVATE_KEY_FILE"

echo_info "Configuring WireGuard server..."
WG_SERVER_PRIVATE_KEY=$(cat "$WG_PRIVATE_KEY_FILE")

cat > "${WG_CONFIG_DIR}/${WG_INTERFACE}.conf" <<EOF
[Interface]
PrivateKey = ${WG_SERVER_PRIVATE_KEY}
Address = ${WG_SERVER_ADDRESS}
ListenPort = ${WG_PORT}
PostUp = iptables -A FORWARD -i ${WG_INTERFACE} -j ACCEPT; \
          iptables -A FORWARD -i ${WAN_INTERFACE} -o ${WG_INTERFACE} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT; \
          iptables -t nat -A POSTROUTING -o ${WAN_INTERFACE} -j MASQUERADE; \
          ip6tables -A FORWARD -i ${WG_INTERFACE} -j ACCEPT; \
          ip6tables -A FORWARD -i ${WAN_INTERFACE} -o ${WG_INTERFACE} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT; \
          ip6tables -t nat -A POSTROUTING -o ${WAN_INTERFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i ${WG_INTERFACE} -j ACCEPT; \
           iptables -D FORWARD -i ${WAN_INTERFACE} -o ${WG_INTERFACE} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT; \
           iptables -t nat -D POSTROUTING -o ${WAN_INTERFACE} -j MASQUERADE; \
           ip6tables -D FORWARD -i ${WG_INTERFACE} -j ACCEPT; \
           ip6tables -D FORWARD -i ${WAN_INTERFACE} -o ${WG_INTERFACE} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT; \
           ip6tables -t nat -D POSTROUTING -o ${WAN_INTERFACE} -j MASQUERADE

[Peer]
PublicKey = ${CLIENT_PUBLIC_KEY}
AllowedIPs = ${WG_SERVER_PEER_ALLOWED_IPS}
EOF

chmod 600 "${WG_CONFIG_DIR}/${WG_INTERFACE}.conf"

echo_info "Enabling IP forwarding..."
cat > /etc/sysctl.d/99-wireguard.conf <<EOF
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
EOF
sysctl --system

echo_info "Configuring firewall..."
iptables -F
iptables -X
ip6tables -F
ip6tables -X

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT ACCEPT

iptables -A INPUT -i lo -j ACCEPT
ip6tables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
if [ "$ENABLE_SSH" = "true" ]; then
    iptables -A INPUT -p tcp --dport 22 -j ACCEPT
    ip6tables -A INPUT -p tcp --dport 22 -j ACCEPT
fi
iptables -A INPUT -p udp --dport "${WG_PORT}" -j ACCEPT
ip6tables -A INPUT -p udp --dport "${WG_PORT}" -j ACCEPT
# ICMP hardening (issue #10): do not accept ICMP echo from the Internet.
# Keep ICMP types required for Path MTU Discovery so the tunnel stays healthy,
# and only allow ping (echo-request) coming from the WireGuard tunnel interface.
iptables -A INPUT -p icmp --icmp-type fragmentation-needed -j ACCEPT
iptables -A INPUT -i "${WG_INTERFACE}" -p icmp --icmp-type echo-request -j ACCEPT
# ICMPv6 is required for correct IPv6 operation (Neighbor Discovery, PMTUD).
ip6tables -A INPUT -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type neighbour-solicitation -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type neighbour-advertisement -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
ip6tables -A INPUT -i "${WG_INTERFACE}" -p icmpv6 --icmpv6-type echo-request -j ACCEPT

iptables-save > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6
netfilter-persistent save
systemctl enable netfilter-persistent
if [ "$ENABLE_SSH" = "true" ]; then
    systemctl enable --now ssh
fi

echo_info "Configuring WireGuard to start on boot..."
systemctl enable "wg-quick@${WG_INTERFACE}"

SERVER_PUBLIC_IP=$(get_public_ip)

echo_info "Starting WireGuard..."
wg-quick up "$WG_INTERFACE" 2>/dev/null || true

echo ""
echo "======================================================================"
echo "WireGuard VPN Server Setup Complete!"
echo "======================================================================"
echo ""
echo "Server public IP: ${SERVER_PUBLIC_IP}"
echo "WireGuard port: ${WG_PORT}"
echo ""
echo "Security notes:"
if [ "$ENABLE_SSH" = "true" ]; then
    echo "  - DEBUG MODE: SSH is ENABLED (VM firewall + NSG allow port 22)"
    echo "  - SSH uses key-based authentication only; the admin account has no password"
    echo "  - The admin account has passwordless (NOPASSWD) sudo"
else
    echo "  - SSH is NOT installed/enabled; port 22 is closed in the VM firewall (no NSG rule)"
fi
echo "  - IP forwarding is enabled"
echo "  - Firewall rules are persistent"
echo "  - WireGuard will start automatically on boot"
echo "======================================================================"
